MyProfile/urls.py
from django.urls import path
from . import views
from . import ajaxviews

app_name='MyProfile'

urlpatterns = [
	path('', views.index, name='index'),
	path('myorders', views.myorders, name='myorders'),
	path('vieworder/<int:pk>', views.vieworder, name='vieworder'),
	path('cart', views.getcart, name='cart'),
	path('updatecart', views.updatecart, name='updatecart'),
	path('deletecartitem/<int:pk>', views.deletecartitem, name='deletecartitem'),
	path('checkout', views.checkout, name='checkout'),
	path('selectaddress', views.selectaddress, name='selectaddress'),
	path('deleteaddress/<int:pk>', views.deleteaddress, name='deleteaddress'),
	path('shippingdetails', views.shippingdetails, name='shippingdetails'),

	path('getstates', ajaxviews.getstates, name='getstates'),
	path('getlocation', ajaxviews.getlocation, name='getlocation'),
	path('locationfrompin', ajaxviews.locationfrompin, name='locationfrompin'),

	path('payment', views.payment, name='payment'),
	path('paymentcomplete', views.paymentcomplete, name='paymentcomplete'),
	path('ordermessage', views.ordermessage, name='ordermessage'),
]

adventuresofnicky/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('summernote/', include('django_summernote.urls')),
    path('verification/', include('verify_email_custom.urls')),
    path('admin/', admin.site.urls),

    path('resetpassword/', auth_views.PasswordResetView.as_view(template_name='passwordreset/passwordreset.html'),name='reset_password'),
    path('resetpasswordsent/', auth_views.PasswordResetDoneView.as_view(template_name='passwordreset/passwordresetsent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='passwordreset/passwordresetconfirm.html'), name='password_reset_confirm'),
    path('passwordresetcomplete/', auth_views.PasswordResetCompleteView.as_view(template_name='passwordreset/passwordresetcomplete.html'), name='password_reset_complete'),

    path('', include('home.urls'), name='homepage'),
    path('author/', include('author.urls'), name='author'),
    path('books/', include('books.urls'), name='books'),
    path('blog/', include('blog.urls'), name='blog'),
    path('reviews/', include('reviews.urls'), name='reviews'),
    path('videos/', include('videos.urls'), name='videos'),
    path('contact/', include('contact.urls'), name='contact'),
    path('login/', include('login.urls'), name='login'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('profile/', include('MyProfile.urls')),
] 
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from django.conf.urls import (
handler400, handler403, handler404, handler500
)

# handler400 = 'my_app.views.bad_request'
# handler403 = 'my_app.views.permission_denied'
handler404 = 'login.views.urlError'
handler500 = 'login.views.ServerError'

blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns = [
	path('', views.index, name='index'),
	path('add-post', views.addBlogPost, name='addBlogPost'),
	path('delete-post/<str:slug>', views.deleteBlogPost, name='deleteBlogPost'),
	path('edit-post/<str:slug>', views.editBlogPost, name='editBlogPost'),

	path('<str:slug>', views.viewblog, name='viewblog'),#this has to always be in the last
]

login/urls.py
from django.urls import path
from . import views

app_name='login'

urlpatterns = [
	path('', views.index, name='index'),
	path('register', views.register, name='register'),
	# path('failedlink', views.requestNewLink, name='request-new-link'),
]

login/models.py
from django.db import models

# Create your models here.

login/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, get_user_model
from accounts.models import User
from django.contrib import messages
from django.shortcuts import redirect
from accounts.forms import UserForm
from verify_email_custom.email_handler import send_verification_email
from home.errorfunction import convertformerror

def index(request):
	if request.user.is_authenticated:
		return redirect("/profile/")
	if request.method == 'POST':
		user = authenticate(email=request.POST['email'], password=request.POST['password'])
		if user is not None:
			login(request, user)
			if request.GET.get('next'):
				return redirect(request.GET.get('next'))
			return redirect('/')
		else:
			url = request.get_full_path()
			messages.error(request,'Please check you credentials')
			return redirect(url)
	if request.GET.get('next'):
		messages.error(request,'Please login to continue')
	return render(request,'login/index.html')

def register(request):
	if request.method == 'POST':
		if request.POST['password'] != request.POST['confirm_password']:
			messages.error(request,'Passwords dont match')
			return redirect('/login/register')
		if User.objects.filter(email=request.POST['email']):
			messages.error(request,'Email already present')
			return redirect('/login/register')
		form = UserForm(request.POST)
		if form.is_valid():
			user = form.save(commit=False)
			password=form.cleaned_data['password']
			user.set_password(password)
			user.save()
			user = send_verification_email(request, form)
			if user:
				text='A verification Link has been sent to your email'
			else:
				text='There is some error sending the email'
			messages.success(request,text)
		else:
			print(form.errors)
			return HttpResponse(convertformerror(form.errors))
		return redirect('/login')
	return render(request,'login/register.html')

def urlError(request,exception):
	return render(request, 'login/errors/404error.html')

def ServerError(request):
	return render(request, 'login/errors/500error.html')

login/templates/login/index.html
{% extends 'components/base.html' %}
{% block content %}

<div id="content" class="yui3-g">
    <div id="main-column" class="yui3-u-2-3">
        <table width="770" border="0" align="center" cellpadding="0" cellspacing="0">
            <tbody><tr valign="top">
                <td valign="top">
                    <form method="post">
                        <table border="0" align="center" cellpadding="0" cellspacing="0">
                        {% csrf_token %}
                        {% if messages %}
                        {% for message in messages %}
                            <h2 class="text-center">{{ message }}</h2>
                        {% endfor %}
                        {% endif %}
                        <input type="hidden" name="next" value="{{ request.GET.next }}">                          
                            <tbody><tr>
                                <td width="38" height="10"> </td>
                                <td height="10"> </td>
                                <td width="36" height="10"> </td>
                            </tr>
                            <tr>
                                <td width="38"> </td>
                                <td valign="middle">
                                    <span style="color:red"></span>
                                    <table width="400" border="0" align="center" cellpadding="0" cellspacing="0">
                                        <tbody><tr class="pagestyle12px">
                                            <td>
                                                Email :
                                            </td>
                                            <td data-children-count="1">
                                                <input type="text" name="email" required>
                                            </td>
                                        </tr>
                                        <tr class="pagestyle12px">
                                            <td>
                                                Password :
                                            </td>
                                            <td data-children-count="1">
                                                <input type="password" name="password" required>
                                            </td>
                                        </tr>
                                        
                                        <tr class="pagestyle12px">
                                            <td align="center" colspan="2"><input type="submit" name="" value="Login">
                                                <a href="{% url 'login:register' %}"><input type="button" name="" value="Register"></a></td>
                                            </tr>
                                        </tbody></table>
                                    </td>
                                    <td width="36"></td>
                                </tr>
                                <tr style="text-align: center;">
                                    <td colspan="2">
                                        <a href="{% url 'reset_password' %}">Forgot password</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td width="38" height="10"></td>
                                    <td height="10"></td>
                                    <td width="36" height="10"></td>
                                </tr>
                            </tbody></table>
                        </form>
                        {% if request.GET.next %}
                        <h3 class="text-center" style="margin: 0px;">OR</h3>
                        <tr class="text-center">
                            <td colspan="2">
                                <form action="{% url 'MyProfile:shippingdetails' %}">
                                    <input type="hidden" name="bookpath" value="{{ request.GET.next }}">
                                    <button href="" class="btn btn-primary" style="color: white;">Continue as guest</button>
                                </form>
                            </td>
                        </tr>   
                        {% endif %}
                        <table width="100%" border="0" align="center" cellpadding="5" cellspacing="0">
                            <tbody><tr>
                                <td width="100%" height="10">&nbsp; </td>
                            </tr>
                        </tbody></table>
                    </td>
                </tr>
            </tbody></table>
        </div>
   {% endblock %}

login/templates/login/problemurl.html
{% extends 'components/base.html' %}
{% block content %}
<style>
    h1{
        letter-spacing: normal;
        word-spacing: normal;
        margin: 0;
        text-align: center;
    }
</style>
<br><br><br>
<div style="margin-top: 100px; margin-bottom: 100px;">
<h1 style="font-size: 25px;">{{ message }}</h1>
</div>
<br><br><br>

{% endblock %}

login/templates/login/register.html
{% extends 'components/base.html' %}
{% block content %}



<div id="content" class="yui3-g">
    <div id="main-column" class="yui3-u-2-3">
        <table width="770" border="0" align="center" cellpadding="0" cellspacing="0">
            <tbody><tr valign="top">
                <td valign="top">
                    <form method="post">
                        {% if messages %}
                        {% for message in messages %}
                            <h3 style="text-align: center; font-size: 24px;">{{ message }}</h3>
                        {% endfor %}
                        {% endif %}
                        {% csrf_token %}
                        <table border="0" align="center" cellpadding="0" cellspacing="0">
                            <tbody><tr>
                                <td width="38" height="10"> </td>
                                <td height="10"> </td>
                                <td width="36" height="10"> </td>
                            </tr>
                            <tr>
                                <td width="38"> </td>
                                <td valign="middle">
                                    <table width="400" border="0" align="center" cellpadding="0" cellspacing="0">
                                        <tbody><tr><td><span style="color:red"></span></td></tr>
                                            <tr class="pagestyle12px">
                                                <td>
                                                    <span style="color:red">*</span>First name :
                                                </td>
                                                <td data-children-count="1">
                                                    <input id="first_name" type="text" name="first_name" required>
                                                </td>
                                            </tr>
                                            <tr class="pagestyle12px">
                                                <td>
                                                    <span style="color:red">*</span>Last name :
                                                </td>
                                                <td data-children-count="1">
                                                    <input id="last_name" type="text" name="last_name" required>
                                                </td>
                                            </tr>
                                            <tr class="pagestyle12px">
                                                <td>
                                                    <span style="color:red">*</span>Email :
                                                </td>
                                                <td data-children-count="1">
                                                    <input id="email" type="email" name="email" required>
                                                </td>
                                            </tr>
                                            <tr class="pagestyle12px">
                                                <td>
                                                    <span style="color:red">*</span>Password :
                                                </td>
                                                <td data-children-count="1">
                                                    <input id="password" type="password" name="password" required>
                                                </td>
                                            </tr>
                                            <tr class="pagestyle12px">
                                                <td>
                                                    <span style="color:red">*</span>Confirm Password :
                                                </td>
                                                <td data-children-count="1">
                                                    <input id="confirm_password" type="password" name="confirm_password" required>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td>
                                                </td>
                                            </tr>
                                            <tr class="pagestyle12px">
                                                <td align="center" colspan="2"><input type="submit" name="" value="Submit"></td>
                                            </tr>
                                        </tbody></table>

                                    </td>
                                    <td width="36"></td>
                                </tr>
                                <tr>
                                    <td width="38" height="10"></td>
                                    <td height="10"></td>
                                    <td width="36" height="10"></td>
                                </tr>
                            </tbody></table>
                        </form>
                        <table width="100%" border="0" align="center" cellpadding="5" cellspacing="0">
                            <tbody><tr>
                                <td width="100%" height="10">&nbsp; </td>
                            </tr>
                        </tbody></table>
                    </td>
                </tr>
            </tbody></table>
   {% endblock %}

login/templates/login/requestnewlink.html
{% extends 'components/base.html' %}
{% block content %}

<div id="content" class="yui3-g">
    <div id="main-column" class="yui3-u-2-3">
        <table width="770" border="0" align="center" cellpadding="0" cellspacing="0">
            <tbody><tr valign="top">
                <td valign="top">
                    <form method="post" class="text-center">
                        <table border="0" align="center" cellpadding="0" cellspacing="0">
                        {% csrf_token %}
                        {% if messages %}
                        {% for message in messages %}
                            <h2 class="text-center">{{ message }}</h2>
                        {% endfor %}
                        {% endif %}
                        <input type="hidden" name="link" value="{{ request.get_full_path }}">
                        <a href="{{ url }}" class="btn btn-success">request</a>
                        <tr><td></td></tr>
                        <!-- <tr><td><input type="submit" name="" value="Request new link"></td></tr> -->
                    </td>
                        </form>
                        <table width="100%" border="0" align="center" cellpadding="5" cellspacing="0">
                            <tbody><tr>
                                <td width="100%" height="10">&nbsp; </td>
                            </tr>
                        </tbody></table>
                    </td>
                </tr>
            </tbody></table>
        </div>
   {% endblock %}