accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns = [
	path('', views.index, name='index'),
	path('manage-blog', views.manageBlog, name='manageBlog'),
	path('manage-taxes', views.manageTaxes, name='manageTaxes'),
	path('deletetax/<int:pk>', views.deletetax, name='deletetax'),
	path('manage-books', views.manageBooks, name='manageBooks'),
	path('deletebook/<int:pk>', views.deletebook, name='deletebook'),
	path('manage-reviews', views.manageReviews, name='manageReviews'),
	path('manage-messages', views.manageMessages, name='manageMessages'),
	path('videos', views.manageVideos, name='manageVideos'),
	path('shipping', views.shipping, name='shipping'),
	path('deleteshipping/<int:pk>', views.deleteshipping, name='deleteshipping'),
	path('orders', views.orders, name='orders'),
	path('updateorder/<int:pk>',views.updateorder, name='updateorder'),
	path('users', views.manageUsers, name='manageUsers'),
]

adventuresofnicky/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('summernote/', include('django_summernote.urls')),
    path('verification/', include('verify_email_custom.urls')),
    path('admin/', admin.site.urls),

    path('resetpassword/', auth_views.PasswordResetView.as_view(template_name='passwordreset/passwordreset.html'),name='reset_password'),
    path('resetpasswordsent/', auth_views.PasswordResetDoneView.as_view(template_name='passwordreset/passwordresetsent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='passwordreset/passwordresetconfirm.html'), name='password_reset_confirm'),
    path('passwordresetcomplete/', auth_views.PasswordResetCompleteView.as_view(template_name='passwordreset/passwordresetcomplete.html'), name='password_reset_complete'),

    path('', include('home.urls'), name='homepage'),
    path('author/', include('author.urls'), name='author'),
    path('books/', include('books.urls'), name='books'),
    path('blog/', include('blog.urls'), name='blog'),
    path('reviews/', include('reviews.urls'), name='reviews'),
    path('videos/', include('videos.urls'), name='videos'),
    path('contact/', include('contact.urls'), name='contact'),
    path('login/', include('login.urls'), name='login'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('profile/', include('MyProfile.urls')),
] 
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from django.conf.urls import (
handler400, handler403, handler404, handler500
)

# handler400 = 'my_app.views.bad_request'
# handler403 = 'my_app.views.permission_denied'
handler404 = 'login.views.urlError'
handler500 = 'login.views.ServerError'

author/urls.py
from django.urls import path
from . import views
app_name='author'
urlpatterns = [
	path('', views.index, name='index'),
	path('addauthordetail', views.addauthordetail, name='addauthordetail'),
	path('addEditSocial', views.addEditSocial, name='addEditSocial'),
	path('deletesocial/<int:pk>', views.deletesocial, name='deletesocial'),
]

blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns = [
	path('', views.index, name='index'),
	path('add-post', views.addBlogPost, name='addBlogPost'),
	path('delete-post/<str:slug>', views.deleteBlogPost, name='deleteBlogPost'),
	path('edit-post/<str:slug>', views.editBlogPost, name='editBlogPost'),

	path('<str:slug>', views.viewblog, name='viewblog'),#this has to always be in the last
]

books/urls.py
from django.urls import path
from . import views

app_name='books'

urlpatterns = [
	path('', views.index, name='index'),
	path('addbook',views.addbook, name='addbook'),
	path('editbook/<str:slug>', views.editbook, name='editbook'),
	path('view/<str:slug>', views.viewbook, name='viewbook'),
	path('addtocart/<str:slug>', views.addtocart, name='addtocart'),
]

contact/urls.py
from django.urls import path
from . import views
app_name='contact'
urlpatterns = [
	path('', views.index, name='index'),
	path('view/<int:pk>', views.viewmessage, name='viewmessage'),
	path('delete/<int:pk>', views.deletemessage, name='deletemessage'),
]

videos/urls.py
from django.urls import path
from . import views

app_name='videos'

urlpatterns = [
	path('', views.index, name='index'),
	path('addvideo', views.addvideo, name='addvideo'),
	path('editvideo/<int:pk>', views.editvideo, name='editvideo'),
	path('deletevideo/<int:pk>', views.deletevideo, name='deletevideo'),
	path('<str:slug>', views.viewvideo, name='viewvideo'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from .ModelManager import UserManager
from datetime import datetime

class User(AbstractBaseUser):
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	email = models.CharField(max_length=100, unique=True)
	is_active = models.BooleanField(default=True)
	staff = models.BooleanField(default=False)
	admin = models.BooleanField(default=False)
	USERNAME_FIELD = 'email'
	objects = UserManager()
	@property
	def is_staff(self):
		return self.staff
	@property
	def is_admin(self):
		return self.admin
	def has_perm(self, perm, obj=None):
		return True
	def has_module_perms(self, app_lable):
		return True


class Country(models.Model):
	countryname = models.CharField(max_length=30)
	def __str__(self):
		return self.countryname

class State(models.Model):
	statename = models.CharField(max_length=50)
	country = models.ForeignKey(Country, on_delete=models.CASCADE)
	def __str__(self):
		return self.statename

class Location(models.Model):
	pincode = models.IntegerField()
	city = models.CharField(max_length=50)
	state = models.ForeignKey(State, on_delete=models.CASCADE)	
	def __str__(self):
		return str(self.pincode)+" "+self.city

class CardType(models.Model):
	card_name = models.CharField(max_length=50)

	def __str__(self):
		return self.card_name

class CustomerAddress(models.Model):
	billingFirstname = models.CharField(max_length=100, blank=True, null=True)
	billingLastName = models.CharField(max_length=100, blank=True, null=True)
	billingEmail = models.CharField(max_length=200)
	billingCompany = models.CharField(max_length=200, blank=True, null=True)
	billingAddress = models.CharField(max_length=200, blank=True, null=True)
	billingPhone = models.CharField(max_length=15, blank=True, null=True)
	billingFax = models.CharField(max_length=15, blank=True, null=True)
	billingLocation = models.ForeignKey(Location, on_delete=models.RESTRICT, related_name='billing')

	shippingFirstname = models.CharField(max_length=100, blank=True, null=True)
	shippingLastName = models.CharField(max_length=100, blank=True, null=True)
	shippingEmail = models.CharField(max_length=200)
	shippingCompany = models.CharField(max_length=200, blank=True, null=True)
	shippingAddress = models.CharField(max_length=200, blank=True, null=True)
	shippingPhone = models.CharField(max_length=15, blank=True, null=True)
	shippingFax = models.CharField(max_length=15, blank=True, null=True)
	shippingLocation = models.ForeignKey(Location, on_delete=models.RESTRICT, related_name='shipping')

	active = models.BooleanField(default=True)
	# CC_type = models.ForeignKey('CardType', on_delete=models.RESTRICT)
	# CC_number = models.CharField(max_length=30)
	# CC_Expires = models.CharField(max_length=12)
	date_created = models.DateTimeField(default=datetime.now)

	user = models.ForeignKey(User, on_delete=models.RESTRICT,null=True, blank=True)

	def __str__(self):
		return self.billingEmail

accounts/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from accounts.models import User

class AddressForm(forms.ModelForm):
	class Meta:
		exclude = ['date_created']
		model = CustomerAddress
		fields = '__all__'

class UserForm(forms.ModelForm):
	first_name = forms.CharField()
	last_name = forms.CharField()
	email = forms.EmailField()
	class Meta:
		model = User
		fields = ('first_name','last_name','email','password')
		# fields = '__all__'


# class UserForm(forms.Form):
# 	first_name = forms.CharField(max_length=100)
# 	last_name = forms.CharField(max_length=100)
# 	email = forms.CharField(max_length=100)
# 	password = forms.CharField(label='Confirm password', widget=forms.PasswordInput)
# 	def save(self, commit=True):
# 		user = User.objects.create_user(
# 			self.cleaned_data['first_name'],
# 			self.cleaned_data['last_name'],
# 			self.cleaned_data['email'],
# 			self.cleaned_data['password']
# 		)
# 		return user

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from author.forms import AuthorForm
from author.models import *
from blog.models import BlogPost
from books.models import *
from books.forms import *
from reviews.models import *
from contact.models import *
from videos.models import *
from home.errorfunction import convertformerror
from .otherfunctions import sendmailupdate

notaccesscontext={'message':'you cannot access this section'}
notloggedincontext={'message':'Please login with an admin accout'}


def index(request):
	if not request.user.is_authenticated:
		return render(request,'login/problemurl.html',notloggedincontext)
	if not request.user.is_admin:		
		return render(request,'login/problemurl.html',notaccesscontext)
	context = {
		'authorform':AuthorForm(instance=Author.objects.all().first()),
		'socials':SocialMedia.objects.all(),
	}
	return render(request,'accounts/manage_author.html',context)

def manageBlog(request):
	if not request.user.is_authenticated:
		return render(request,'login/problemurl.html',notloggedincontext)
	if not request.user.is_admin:		
		return render(request,'login/problemurl.html',notaccesscontext)
	blogs = BlogPost.objects.all()
	return render(request,'accounts/manage_blog.html', {'blogs':blogs})

def manageTaxes(request):
	if not request.user.is_authenticated:
		return render(request,'login/problemurl.html',notloggedincontext)
	if not request.user.is_admin:		
		return render(request,'login/problemurl.html',notaccesscontext)
	if request.method == 'POST':
		if request.POST['pk']:
			form = TaxesForm(request.POST, instance=Taxes.objects.get(pk=request.POST['pk']))
		else:
			form = TaxesForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/accounts/manage-taxes')
		else:
			return HttpResponse(form.errors)
	taxes = Taxes.objects.all()
	return render(request,'accounts/manage_taxes.html',{'taxes':taxes})

def deletetax(request,pk):
	tax = Taxes.objects.get(pk=pk)
	tax.delete()
	return redirect('/accounts/manage-taxes')

def manageBooks(request):
	if not request.user.is_authenticated:
		return render(request,'login/problemurl.html',notloggedincontext)
	if not request.user.is_admin:		
		return render(request,'login/problemurl.html',notaccesscontext)
	books = Product.objects.all()
	return render(request,'accounts/manage_books.html',{'books':books})

def deletebook(request,pk):
	book = Product.objects.get(pk=pk)
	return HttpResponse(book)
	book.delete()
	return redirect('/accounts/manage-books/')

def manageReviews(request):
	if not request.user.is_authenticated:
		return render(request,'login/problemurl.html',notloggedincontext)
	if not request.user.is_admin:		
		return render(request,'login/problemurl.html',notaccesscontext)
	reviews = Review.objects.all()
	return render(request,'accounts/manage_reviews.html',{'reviews':reviews})

def manageMessages(request):
	if not request.user.is_authenticated:
		return render(request,'login/problemurl.html',notloggedincontext)
	if not request.user.is_admin:		
		return render(request,'login/problemurl.html',notaccesscontext)
	messages = Message.objects.all()
	return render(request,'accounts/manage_messages.html',{'messages':messages})

def manageVideos(request):
	if not request.user.is_authenticated:
		return render(request,'login/problemurl.html',notloggedincontext)
	if not request.user.is_admin:		
		return render(request,'login/problemurl.html',notaccesscontext)
	videos = VideoPost.objects.all()
	return render(request,'accounts/manage_videos.html',{'videos':videos})

def shipping(request):
	if request.method == 'POST':
		if request.POST['pk']:
			pk = request.POST['pk']
			form = ShippingForm(request.POST, instance=ShippingFee.objects.get(pk=pk))
		else:
			form = ShippingForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('/accounts/shipping')
		else:
			return HttpResponse(convertformerror(form.errors))
	shippingfees = ShippingFee.objects.all()
	return render(request, 'accounts/shipping.html',{'shippingfees':shippingfees})

def deleteshipping(request, pk):
	shipping = ShippingFee.objects.get(pk=pk)
	shipping.delete()
	return redirect('/accounts/shipping')

def orders(request):
	orders = Orders.objects.all()
	return render(request,'accounts/manage_orders.html',{'orders':orders})

def updateorder(request,pk):
	if request.method == 'POST':
		form = OrderForm(request.POST, instance=Orders.objects.get(pk=pk))
		if form.is_valid():
			saved = form.save()
			if form.instance.itemtype == 'paperback':
				sendmailupdate(Orders.objects.get(pk=pk))
			return redirect('/accounts/updateorder/'+str(saved.pk))
		else:
			return HttpResponse(convertformerror(form.errors))
	order = Orders.objects.get(pk=pk)
	return render(request, 'accounts/updateOrder.html',{'order':order})

def manageUsers(request):
	if request.method == 'POST':
		user = User.objects.get(pk=request.POST['pk'])
		if request.POST.get('is_active'):
			user.is_active = True
		else:
			user.is_active = False
		user.save()
		return redirect('/accounts/users')
	users = User.objects.all()
	return render(request,'accounts/manage_users.html',{'users':users})

accounts/templates/accounts/baseAccount.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>
		{% block title %}
		{% endblock %}
	</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	{% load static %}
	<link href="{% static 'accounts/styles.css' %}" rel="stylesheet" />
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
</head>
<body>
	<div class="d-flex" id="wrapper">
		<div class="bg-light border-right" id="sidebar-wrapper">
			<div class="sidebar-heading">Nicky Dashboard</div>
			<div class="list-group list-group-flush">
				<a href="{% url 'accounts:index' %}" class="sidebar-list {% if request.path == '/accounts/' %}active{% endif %}">Author</a>
				<a href="{% url 'accounts:manageBlog' %}" class="sidebar-list {% if request.path == '/accounts/manage-blog' or '/blog/' in request.path %}active{% endif %}">Blog</a>
				<a href="{% url 'accounts:manageTaxes' %}" class="sidebar-list {% if request.path == '/accounts/manage-taxes' %}active{% endif %}">Taxes</a>
				<a href="{% url 'accounts:manageBooks' %}" class="sidebar-list {% if request.path == '/accounts/manage-books' %}active{% endif %}">Books</a>
				<a href="{% url 'accounts:manageReviews' %}" class="sidebar-list {% if request.path == '/accounts/manage-reviews' or '/reviews/' in request.path %}active{% endif %}">Reviews</a>
				<a href="{% url 'accounts:manageVideos' %}" class="sidebar-list {% if request.path == '/accounts/videos' %}active{% endif %}">Videos</a>
				<a href="{% url 'accounts:manageMessages' %}" class="sidebar-list {% if request.path == '/accounts/manage-messages' or '/contact/' in request.path %}active{% endif %}">Messages</a>
				<a href="{% url 'accounts:shipping' %}" class="sidebar-list {% if request.path == '/accounts/shipping'%}active{% endif %}">Shipping</a>
				<!-- <a href="{% url 'accounts:manageUsers' %}" class="sidebar-list {% if request.path == '/accounts/users'%}active{% endif %}">Users</a> -->
				<a href="{% url 'accounts:orders' %}" class="sidebar-list {% if request.path == '/accounts/orders' %}active{% endif %}">Orders</a>
				<a href="/" class="sidebar-list">Home</a>

			</div>
		</div>
		<i class="fa fa-bars text-right sidebar-icon" id="menu-toggle" style=""></i>
		<div id="page-content-wrapper">
			{% block content %}
			{% endblock %}
		</div>
	</div>
	
</body>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
	<script>
		$("#menu-toggle").click(function(e) {
	  		e.preventDefault();
	  		$("#wrapper").toggleClass("toggled");
		});
  </script>
</html>

accounts/templates/accounts/manage_author.html
{% extends 'accounts/baseAccount.html' %}
{% block title %}
	Manage author
{% endblock %}
{% block content %}
<div class="text-center">
	<div style="border: 1px solid black;">
	<table class="table table-borderless table-hover">
		<thead class="table-light">
			<tr>
				<th colspan="4"><h3>Social Media </h3></th>
			</tr>
			<tr>
				<th>Name</th>
				<th>Title</th>
				<th></th>
				<th></th>
			</tr>
		</thead>
		{% for social in socials %}
		<tr>
			<td>{{ social.name }}</td>
			<td>{{ social.title }}</td>
			<td>
				{% if social.icon %}
					<a href="{{ social.icon.url }}" target='_blank'> current </a>
				{% else %}
					No icon present
				{% endif %}
			</td>
			<td>
				<button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#add_modal_social" onclick="editsocialdata('{{social.pk}}','{{social.name}}','{{social.title}}','{{social.url}}')">Edit</button>
				<button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal" onclick="changemodal('{% url 'author:deletesocial' social.pk %}','{{ social.title }}')">
					Delete
				</button>
			</td>
		</tr>
		{% endfor %}
		<tr>
			<td colspan="4">
				<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#add_modal_social" onclick="editsocialdata('','','','')">
					Add Social
				</button>
			</td>
		</tr>
	</table>
	</div>
	<br>
	<!-- <hr> -->
	<!-- <br> -->
	<div style="border: 1px solid black;">
		<div class="container">
		<h3>Author Content</h3>
		{% if authorform.instance.author_image %}
			<a href="{{ authorform.instance.author_image.url }}" target="_blank">current author image</a>
		{% endif %}
		<br>
		{{ authorform.media }}
		<form method="post" enctype="multipart/form-data" action="{% url 'author:addauthordetail' %}">
			{% csrf_token %}<br>
			<input type="file" name="author_image" accept="image/*" class="form-control"><br>
			<input type="email" name="review_mail" class="form-control" placeholder="email when review posted" value="{{ authorform.instance.review_mail|default:'' }}">
			<br>
			{{ authorform.description }}
			<input type="submit" class="btn btn-outline-success">
		</form>
		<p>Last updated: {{ authorform.instance.updated }}</p>
		</div>
	</div>
</div>
{% include 'accounts/components/add_modal_social.html' %}
{% include 'accounts/components/delete_modal.html' %}
{% endblock %}

accounts/templates/accounts/manage_blog.html
{% extends 'accounts/baseAccount.html' %}
{% block title %}
	Manage Blog
{% endblock %}
{% block content %}
<div class="container text-center">
	<br><h2>Blog Management</h2><br>
	<a href="{% url 'blog:addBlogPost' %}" class="btn btn-info">Add Post</a><br>
	<table class="table">
		{% for blog in blogs %}
		<tr>
			<td><a href="{% url 'blog:viewblog' blog.slug %}" target="_blank">{{ blog.title }}</a></td>
			<td><a href="{% url 'blog:editBlogPost' blog.slug %}" class="btn btn-warning btn-sm">edit</a></td>
			<td>
				<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" onclick="changemodal('{% url 'blog:deleteBlogPost' blog.slug %}','{{ blog.title }}')">
					Delete
				</button>
			</td>
		</tr>
		{% endfor %}
	</table>
</div>

{% include 'accounts/components/delete_modal.html' %}

{% endblock %}

accounts/templates/accounts/manage_books.html
{% extends 'accounts/baseAccount.html' %}
{% block title %}
	Manage Books
{% endblock %}
{% block content %}
<table class="table text-center container mt-2">
	<tr>
		<td colspan="2">
			<a href="{% url 'books:addbook' %}" class="btn btn-primary">Add Book</a>
		</td>
	</tr>
	{% for book in books %}
	<tr>
		<td>{{ book.name }}</td>
		<td>
			<a href="{% url 'books:editbook' book.slug %}" class="btn btn-primary">Edit</a>
			<button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal" onclick="changemodal('{% url 'accounts:deletebook' book.pk %}','{{ book.name }}')">Delete</button>
		</td>
	</tr>
	{% endfor %}
</table>
{% include 'accounts/components/delete_modal.html' %}
{% endblock %}

accounts/templates/accounts/manage_messages.html
{% extends 'accounts/baseAccount.html' %}
{% block title %}
	Manage Messages
{% endblock %}
{% block content %}
	<table class="table table-borderless text-center container">
		<thead>
			<tr>
				<th>Name</th>
				<th>Email</th>
				<th>subject</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			{% for message in messages %}
			<tr>
				<td>
					<a href="{% url 'contact:viewmessage' message.pk %}">
					{{ message.name }}
					</a>
				</td>
				<td>{{ message.email }}</td>
				<td>{{ message.subject }}</td>
				<td>
					<!-- <button class="btn btn-danger">Delete</button> -->
					<button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal" onclick="changemodal('{% url 'contact:deletemessage' message.pk %}','{{ message.subject }}')">Delete</button>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% include 'accounts/components/delete_modal.html' %}
{% endblock %}

accounts/templates/accounts/manage_orders.html
{% extends 'accounts/baseAccount.html' %}
{% block title %}
	Manage Orders
{% endblock %}
{% block content %}

<table class="table text-center">
	<thead>
		<tr>
			<td>Book</td>
			<td>type</td>
			<td>quantity</td>
			<td>Location</td>
			<td></td>
		</tr>
	</thead>
	<tr><td colspan="5"><h4>Pending</h4></td></tr>
	{% for order in orders %}
		{% if not order.completed %}
		<tr>
			<td>{{ order.product }}</td>
			<td>{{ order.itemtype }}</td>
			<td>{{ order.quantity }}</td>
			<td>{{ order.address.shippingLocation.city }}</td>
			<td><a href="{% url 'accounts:updateorder' order.pk %}" class="btn btn-primary">View/Update</a></td>
		</tr>
		{% endif %}
	{% endfor %}
</table>

<table class="table text-center">
	<tr><td colspan="5"><h4>Completed</h4></td></tr>
	{% for order in orders %}
		{% if order.completed %}
		<tr>
			<td>{{ order.product }}</td>
			<td>{{ order.itemtype }}</td>
			<td>{{ order.quantity }}</td>
			<td>{{ order.address.shippingLocation.city }}</td>
			<td><a href="{% url 'accounts:updateorder' order.pk %}" class="btn btn-primary">View/Update</a></td>
		</tr>
		{% endif %}
	{% endfor %}
</table>
{% endblock %}

accounts/templates/accounts/manage_taxes.html
{% extends 'accounts/baseAccount.html' %}
{% block title %}
	Manage Taxes
{% endblock %}
{% block content %}
<br>
<center>
	<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addTaxModal" onclick="edittax('','','','')">
		Add Tax
	</button>
</center><br>
<table class="table thead-dark text-center container">
	<thead>
		<tr>
			<th>Name</th>
			<th>Percentage</th>
			<th>Description</th>
			<th></th>
		</tr>
	</thead>
	{% for tax in taxes %}
		<tr>
			<td>{{ tax.name }}</td>
			<td>{{ tax.percentage }}</td>
			<td>{{ tax.description }}</td>
			<td>
				<button class="btn btn-primary" onclick="edittax('{{ tax.pk }}','{{ tax.name }}','{{ tax.percentage }}','{{ tax.description }}')" data-bs-toggle="modal" data-bs-target="#addTaxModal">Edit</button>
				<button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal" onclick="changemodal('{% url 'accounts:deletetax' tax.pk %}','{{ tax.name }}')">Delete</button>
			</td>
		</tr>
	{% endfor %}
</table>
{% include 'accounts/components/add_tax_modal.html' %}
{% include 'accounts/components/delete_modal.html' %}
{% endblock %}

accounts/templates/accounts/manage_videos.html
{% extends 'accounts/baseAccount.html' %}
{% block title %}
	Videos
{% endblock %}
{% block content %}
	<br>
	<table class="table text-center">
		<tr>
			<td colspan="3">
				<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#videosModal" onclick="editvideo(`{% url 'videos:addvideo' %}`,``,``,``)">
					Add Videos
				</button>
			</td>
		</tr>	
	{% for video in videos %}
		<tr>
			<td>{{ video.video_title }}</td>
			<td><a href="{{ video.video_thumbnail.url }}" target="_blank">thumbnail</a></td>
			<td>
				<button onclick="editvideo(`{% url 'videos:editvideo' video.pk %}`,`{{video.video_title}}`,`{{video.video_description|default_if_none:''}}`,`{{video.video_url}}`)" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#videosModal">Edit</button>
				<button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal" onclick="changemodal('{% url 'videos:deletevideo' video.pk %}','{{ video.video_title }}')">Delete</button>
			</td>
		</tr>
	{% endfor %}
	</table>
	{% include 'accounts/components/delete_modal.html' %}
	{% include 'accounts/components/videos_modal.html' %}
{% endblock %}