MyProfile/urls.py
from django.urls import path
from . import views
from . import ajaxviews

app_name='MyProfile'

urlpatterns = [
	path('', views.index, name='index'),
	path('myorders', views.myorders, name='myorders'),
	path('vieworder/<int:pk>', views.vieworder, name='vieworder'),
	path('cart', views.getcart, name='cart'),
	path('updatecart', views.updatecart, name='updatecart'),
	path('deletecartitem/<int:pk>', views.deletecartitem, name='deletecartitem'),
	path('checkout', views.checkout, name='checkout'),
	path('selectaddress', views.selectaddress, name='selectaddress'),
	path('deleteaddress/<int:pk>', views.deleteaddress, name='deleteaddress'),
	path('shippingdetails', views.shippingdetails, name='shippingdetails'),

	path('getstates', ajaxviews.getstates, name='getstates'),
	path('getlocation', ajaxviews.getlocation, name='getlocation'),
	path('locationfrompin', ajaxviews.locationfrompin, name='locationfrompin'),

	path('payment', views.payment, name='payment'),
	path('paymentcomplete', views.paymentcomplete, name='paymentcomplete'),
	path('ordermessage', views.ordermessage, name='ordermessage'),
]

adventuresofnicky/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('summernote/', include('django_summernote.urls')),
    path('verification/', include('verify_email_custom.urls')),
    path('admin/', admin.site.urls),

    path('resetpassword/', auth_views.PasswordResetView.as_view(template_name='passwordreset/passwordreset.html'),name='reset_password'),
    path('resetpasswordsent/', auth_views.PasswordResetDoneView.as_view(template_name='passwordreset/passwordresetsent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='passwordreset/passwordresetconfirm.html'), name='password_reset_confirm'),
    path('passwordresetcomplete/', auth_views.PasswordResetCompleteView.as_view(template_name='passwordreset/passwordresetcomplete.html'), name='password_reset_complete'),

    path('', include('home.urls'), name='homepage'),
    path('author/', include('author.urls'), name='author'),
    path('books/', include('books.urls'), name='books'),
    path('blog/', include('blog.urls'), name='blog'),
    path('reviews/', include('reviews.urls'), name='reviews'),
    path('videos/', include('videos.urls'), name='videos'),
    path('contact/', include('contact.urls'), name='contact'),
    path('login/', include('login.urls'), name='login'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('profile/', include('MyProfile.urls')),
] 
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from django.conf.urls import (
handler400, handler403, handler404, handler500
)

# handler400 = 'my_app.views.bad_request'
# handler403 = 'my_app.views.permission_denied'
handler404 = 'login.views.urlError'
handler500 = 'login.views.ServerError'

blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns = [
	path('', views.index, name='index'),
	path('add-post', views.addBlogPost, name='addBlogPost'),
	path('delete-post/<str:slug>', views.deleteBlogPost, name='deleteBlogPost'),
	path('edit-post/<str:slug>', views.editBlogPost, name='editBlogPost'),

	path('<str:slug>', views.viewblog, name='viewblog'),#this has to always be in the last
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
	path('', views.index, name='index'),
	path('logout/', views.logout_view, name='logout'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import authenticate, logout
from django.shortcuts import redirect
from books.models import Product

def index(request):
	books = Product.objects.all().filter(active=True)
	return render(request, 'home/index.html',{'books':books})

def logout_view(request):
	logout(request)
	return redirect('/')

home/templates/components/base.html
<!DOCTYPE html>
<!-- saved from url=(0040)https://www.adventuresofnicky.com/books/ -->
<html lang="" dir="ltr" id="books" class="simple" crosspilot=""><!--<![endif]--><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
<meta name="description" content="Get all books written by Alessandra Nadudvari available in The Adventures of Nicky book series.">
<meta name="keywords" content="Nicky,book,Alessandra Nadudvari,templar,viking">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>
{% block title %}
{% endblock %}
</title>
<link rel="icon" href="https://www.adventuresofnicky.com/images/nickyIcon.png">
{% load static %}
<link type="text/css" rel="stylesheet" href="{% static 'books/css/custom.css' %}">

</head>
<body>
<div id="cape">
<div id="robe">
<div id="crown"><div class="overlay"></div></div>
    <div id="doc">
    <header>
        <div id="hd" role="banner">
            <a href="/" title="Written by Alessandra Nadudvari" target="_parent"><h2 id="logo"><span>Adventures of Nicky Book Series</span></h2></a>
            <div id="splash">
                <h3><span></span></h3>
            </div>
        </div>
    </header>
    <div id="bd" role="main" class="yui3-g">
        <div id="jump-to_menu" class="yui3-g">
            <div class="content yui3-u-1">
                <p class=""><a href="/">Jump to Menu</a></p>
            </div>
        </div>
        {% block content %}
        {% endblock %}
    {% include 'components/navbar.html' %}
    <footer>
        <div id="ft" role="contentinfo" class="yui3-u-1">
            <address>
                <p class="content">Copyright © Alessandra Nadudvari, 2021</p>
            </address>
        </div>
    </footer>
</div><!-- bd -->
</div><!-- doc -->
<div id="shoe"><div class="overlay"></div></div>
</div><!-- robe -->
</div><!-- cape -->

<iframe src="./Books _ Adventures of Nicky Series_files/saved_resource.html" style="display: none;" __idm_frm__="356"></iframe></body></html>

home/templates/components/navbar.html
<nav>
	<div id="nav" class="yui3-u-1">
		<div id="nav-preload"></div>
		<ul id="mainnav">
			<li class="a">
				<a href="/" title="Back to Homepage of Adventures of Nicky Book Series"><span><h5>Home</h5></span></a>
			</li>
			<li class="aa {% if request.path == '/books/' %} active {% endif %}">
				<a href="/books" title="The Adventures of Nicky Books"><span><h5>Books</h5></span></a>
			</li>
			<li class="ab {% if request.path == '/author/' %} active {% endif %}">
				<a href="/author/" title="About Alessandra Nadudvari"><span><h5>Author</h5></span></a>
			</li>
			<li class="ac {% if request.path == '/blog/' %} active {% endif %}">
				<a href="/blog/" title="Author&#39;s Blog"><span><h5>Blog</h5></span></a>
			</li>
			<li class="ae {% if request.path == '/reviews/' %} active {% endif %}">
				<a href="/reviews/" title="Feedback from Readers"><span><h5>Reviews</h5></span></a>
			</li>
			<li class="ae {% if request.path == '/videos/' %} active {% endif %}">
				<a href="/videos/ " title="Videos of some of those interviews"><span><h5>Videos</h5></span></a>
			</li>
			<li class="af {% if request.path == '/contact/' %} active {% endif %}">
				<a href="/contact/" title="Contact Author"><span><h5>Contact</h5></span></a>
			</li>
			{% if user.is_authenticated %}
			<li class="af {% if request.path == '/profile/' %} active {% endif %}">
				<a href="{% url 'MyProfile:index' %}" title="Profile"><span><h5>Profile</h5></span></a>
			</li>
			<li class="af {% if request.path == '/login/' %} active {% endif %}">
				<a href="{% url 'home:logout' %}" title="Logout"><span><h5>Logout</h5></span></a>
			</li>
			{% else %}
			<li class="af {% if request.path == '/login/' %} active {% endif %}">
				<a href="/login/" title="User Login"><span><h5>Login</h5></span></a>
			</li>
			{% endif %}
		</ul>
	</div>
</nav>

home/templates/components/view_base.html
<!DOCTYPE html>
<html lang="" dir="ltr" id="story-page" class="simple" crosspilot=""><!--<![endif]-->
<head>
	<title>{% block title %}{% endblock %}</title>
	<link rel="icon" href="https://www.adventuresofnicky.com/images/nickyIcon.png">
	{% load static %}
	<link type="text/css" rel="stylesheet" href="{% static 'books/css/custom.css' %}">
</head>
<body>
<div id="cape">
<div id="robe">
<div id="crown"><div class="overlay"></div></div>
<div id="doc">
    <header>
        <div id="hd" role="banner">
            <a href="https://www.adventuresofnicky.com/" title="Written by Alessandra Nadudvari" target="_parent"><h2 id="logo"><span>Adventures of Nicky Book Series</span></h2></a>
            <div id="splash">
                <h3><span></span></h3>
            </div>
        </div>
    </header>

    <div id="bd" role="main" class="yui3-g">
        <div id="jump-to_menu" class="yui3-g">
            <div class="content yui3-u-1">
                <p class=""><a href="">Jump to Menu</a></p>
            </div>
        </div>
{% block content %}
{% endblock %}
{% include 'components/navbar.html' %}
    <footer>
        <div id="ft" role="contentinfo" class="yui3-u-1">
            <address>
                <p class="content">Copyright © Alessandra Nadudvari, 2021</p>
            </address>
        </div>
    </footer>
</div><!-- bd -->
</div><!-- doc -->
<div id="shoe"><div class="overlay"></div></div>
</div><!-- robe -->
</div><!-- cape -->
</body></html>