adventuresofnicky/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('summernote/', include('django_summernote.urls')),
    path('verification/', include('verify_email_custom.urls')),
    path('admin/', admin.site.urls),

    path('resetpassword/', auth_views.PasswordResetView.as_view(template_name='passwordreset/passwordreset.html'),name='reset_password'),
    path('resetpasswordsent/', auth_views.PasswordResetDoneView.as_view(template_name='passwordreset/passwordresetsent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='passwordreset/passwordresetconfirm.html'), name='password_reset_confirm'),
    path('passwordresetcomplete/', auth_views.PasswordResetCompleteView.as_view(template_name='passwordreset/passwordresetcomplete.html'), name='password_reset_complete'),

    path('', include('home.urls'), name='homepage'),
    path('author/', include('author.urls'), name='author'),
    path('books/', include('books.urls'), name='books'),
    path('blog/', include('blog.urls'), name='blog'),
    path('reviews/', include('reviews.urls'), name='reviews'),
    path('videos/', include('videos.urls'), name='videos'),
    path('contact/', include('contact.urls'), name='contact'),
    path('login/', include('login.urls'), name='login'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('profile/', include('MyProfile.urls')),
] 
# + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from django.conf.urls import (
handler400, handler403, handler404, handler500
)

# handler400 = 'my_app.views.bad_request'
# handler403 = 'my_app.views.permission_denied'
handler404 = 'login.views.urlError'
handler500 = 'login.views.ServerError'

blog/urls.py
from django.urls import path
from . import views
app_name='blog'
urlpatterns = [
	path('', views.index, name='index'),
	path('add-post', views.addBlogPost, name='addBlogPost'),
	path('delete-post/<str:slug>', views.deleteBlogPost, name='deleteBlogPost'),
	path('edit-post/<str:slug>', views.editBlogPost, name='editBlogPost'),

	path('<str:slug>', views.viewblog, name='viewblog'),#this has to always be in the last
]

books/urls.py
from django.urls import path
from . import views

app_name='books'

urlpatterns = [
	path('', views.index, name='index'),
	path('addbook',views.addbook, name='addbook'),
	path('editbook/<str:slug>', views.editbook, name='editbook'),
	path('view/<str:slug>', views.viewbook, name='viewbook'),
	path('addtocart/<str:slug>', views.addtocart, name='addtocart'),
]

books/models.py
from django.db import models
from django.template.defaultfilters import slugify
from accounts.models import User
class ShippingFee(models.Model):
	each = models.DecimalField(max_digits=10, decimal_places=2)
	additional = models.DecimalField(max_digits=10, decimal_places=2)
	def __str__(self):
		return str(self.each)+ " "+str(self.additional)

class Taxes(models.Model):
	name = models.CharField(max_length=50)
	percentage = models.DecimalField(max_digits=10, decimal_places=2)
	description = models.TextField(null=True, blank=True)

	def __str__(self):
		return self.name

class Product(models.Model):
	name = models.TextField()
	description = models.TextField(null=True, blank=True)
	active = models.BooleanField(default=True)
	slug = models.SlugField(max_length=700)
	cover_image = models.ImageField(upload_to='book/cover/')
	sample_book = models.FileField(upload_to='book/samples/', null=True, blank=True)
	taxes = models.ManyToManyField(Taxes,blank=True)

	audio = models.FileField(upload_to='book/audio', null=True, blank=True)
	audio_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

	ebook = models.FileField(upload_to='book/audio', null=True, blank=True)
	ebook_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
	
	paperback = models.BooleanField(default=True)
	paperback_quantity = models.IntegerField(null=True, blank=True)
	paperback_price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
	shipping = models.ForeignKey(ShippingFee, null=True, blank=True, on_delete=models.RESTRICT)

	def save(self, *args, **kwargs):
		if not self.slug:
			original_slug = slugify(self.name)
			queryset = Product.objects.all().filter(slug__iexact=original_slug).count()

			count = 1
			slug = original_slug
			while(queryset):
				slug = original_slug + '-' + str(count)
				count += 1
				queryset = Product.objects.all().filter(slug__iexact=slug).count()

			self.slug = slug
		
		super(Product, self).save(*args, **kwargs)

	def __str__(self):
		return self.name 


class Orders(models.Model):
	user = models.ForeignKey(User, on_delete=models.RESTRICT,null=True, blank=True)
	address = models.ForeignKey('accounts.CustomerAddress', on_delete=models.RESTRICT)
	product = models.ForeignKey(Product, on_delete=models.RESTRICT)
	itemtype = models.CharField(max_length=10)
	quantity = models.IntegerField()
	price_total = models.DecimalField(max_digits=10, decimal_places=2)
	date_ordered = models.DateTimeField(auto_now_add=True)
	courier_details = models.TextField(blank=True, null=True)
	shipped_date = models.DateTimeField(blank=True, null=True)
	completed = models.BooleanField(default=False)

	def __str__(self):
		return str(self.address)

class CartItem(models.Model):
	user = models.ForeignKey('accounts.User', on_delete=models.CASCADE, null=True,blank=True)
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	quantity = models.IntegerField(default=1)
	date_added = models.DateTimeField(auto_now_add=True)
	itemtype = models.CharField(max_length=10)
	def __str__(self):
		return str(self.product)

	def getprice(self):
		if self.itemtype == 'ebook':
			price = self.product.ebook_price
		elif self.itemtype == 'paperback':
			price = self.product.paperback_price
		else:
			price = self.product.audio_price
		return price*self.quantity

	def gettax(self):
		price = self.getprice()
		taxes_total = 0
		for taxperc in self.product.taxes.all():
			tax = (price*taxperc.percentage)/100
			taxes_total += tax
		taxes_total = round(taxes_total,2)
		return taxes_total

	def getshipping(self):
		if self.itemtype != 'paperback':
			return 0 # else it is paperback
		if self.quantity == 1:
			return self.product.shipping.each
		else:
			totalshipping = 0
			for i in range(0,self.quantity):
				if i == 0:
					totalshipping += self.product.shipping.each
				else:
					totalshipping += self.product.shipping.additional
			return totalshipping

	def calculatetotal(self):
		price = self.getprice()
		gettax = self.gettax()
		shipping = self.getshipping()
		return (price+gettax+shipping)

books/forms.py
from django import forms
from .models import *

class TaxesForm(forms.ModelForm):
	class Meta:
		model = Taxes
		fields = '__all__'

class BookForm(forms.ModelForm):
	class Meta:
		exclude = ['slug']
		model = Product
		fields = '__all__'

class CartItemForm(forms.ModelForm):
	class Meta:
		exclude = ['quantity','date_added']
		model = CartItem
		
class ShippingForm(forms.ModelForm):
	class Meta:
		model = ShippingFee
		fields = '__all__'

class OrderForm(forms.ModelForm):
	class Meta:
		model = Orders
		fields = ['courier_details','shipped_date','completed']

books/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import *
from home.errorfunction import convertformerror
from .forms import *
from decimal import *
from django.contrib.auth.decorators import login_required

notaccesscontext={'message':'you cannot access this section'}
notloggedincontext={'message':'Please login with an admin accout'}

def index(request):
	books = Product.objects.all().filter(active=True)
	return render(request, 'books/books.html', {'books':books})

def addbook(request):
	if not request.user.is_authenticated:
		return render(request,'login/problemurl.html',notloggedincontext)
	if not request.user.is_admin:		
		return render(request,'login/problemurl.html',notaccesscontext)
	if request.method == 'POST':
		form = BookForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
			return redirect('/accounts/manage-books')
		else:
			return HttpResponse(convertformerror(form.errors))
	taxes = Taxes.objects.all()
	shipping = ShippingFee.objects.all()
	return render(request, 'books/add_book.html',{'taxes':taxes,'shippings':shipping})

def editbook(request,slug):
	if not request.user.is_authenticated:
		return render(request,'login/problemurl.html',notloggedincontext)
	if not request.user.is_admin:		
		return render(request,'login/problemurl.html',notaccesscontext)
	book = Product.objects.get(slug=slug)
	if request.method == 'POST':
		form = BookForm(request.POST, request.FILES, instance=book)
		if form.is_valid():
			form.save()
			return redirect('/accounts/manage-books')
		else:
			return HttpResponse(convertformerror(form.errors))
	taxes = Taxes.objects.all()
	shipping = ShippingFee.objects.all()
	return render(request, 'books/edit_book.html',{'taxes':taxes,'book':book,'shippings':shipping})

def viewbook(request, slug):
	book = Product.objects.get(slug=slug)
	return render(request, 'books/viewbook.html',{'book':book})

@login_required(login_url='/login')
def addtocart(request,slug):
	book = Product.objects.get(slug=slug)
	cartitems = CartItem.objects.filter(product=book).filter(user=request.user)
	cartitems = cartitems.filter(itemtype = request.GET['ptype'])
	if len(cartitems) > 0: # if item present increase quantity
		cartitem = cartitems[0]
		quantity = cartitem.quantity
		cartitem.quantity = quantity+1
	else:
		cartitem = CartItem()
		cartitem.user = request.user
		cartitem.product = book
		cartitem.itemtype = request.GET['ptype']
	cartitem.save()
	return redirect('/profile/cart')

books/templates/books/add_book.html
{% extends 'accounts/baseAccount.html' %}
{% block title %} Add book {% endblock %}
{% block content %}
<form method="post" enctype="multipart/form-data">
<table class="table table-borderless table-hover container mt-5">
	{% csrf_token %}
	<tr>
		<td>Name</td>
		<td><input type="text" name="name" class="form-control" required></td>
	</tr>
	<tr>
		<td>Description</td>
		<td><textarea name="description" cols="30" rows="4" class="form-control"></textarea></td>
	</tr>
	<tr>
		<td><label for="active">active</label></td>
		<td><input type="checkbox" id="active" name="active" checked="true"></td>
	</tr>
	<tr>
		<td>cover image</td>
		<td><input type="file" name="cover_image" class="form-control" required></td>
	</tr>
	<tr>
		<td>Sample book</td>
		<td><input type="file" name="sample_book" class="form-control"></td>
	</tr>
	<tr>
		<td>taxes</td>
		<td>
			<select name="taxes" class="form-control" multiple>
				{% for tax in taxes %}
				<option value="{{ tax.pk }}">{{tax.name}} {{tax.percentage}}%</option>
				{% endfor %}
			</select>
		</td>
	</tr>
	<tr>
		<td>audio file</td>
		<td><input type="file" name="audio" class="form-control"></td>
	</tr>
	<tr>
		<td>audio price</td>
		<td><input type="number" name="audio_price" class="form-control"></td>
	</tr>
	<tr>
		<td>ebook file</td>
		<td><input type="file" name="ebook" class="form-control"></td>
	</tr>
	<tr>
		<td>ebook price</td>
		<td><input type="number" name="ebook_price" class="form-control"></td>
	</tr>
	<tr>
		<td><label for="paper_back">paper back</label></td>
		<td><input id="paper_back" type="checkbox" name="paperback"></td>
	</tr>
	<tr class="paperbackRow">
		<td>paperback quantity</td>
		<td><input type="number" name="paperback_quantity" class="form-control"></td>
	</tr>
	<tr class="paperbackRow">
		<td>paperback price</td>
		<td><input type="number" name="paperback_price" class="form-control"></td>
	</tr>
	<tr class="paperbackRow">
		<td>Shipping</td>
		<td>
			<select name="shipping" class="form-control">
				<option value="">--select shipping--</option>
				{% for shipping in shippings %}
				<option value="{{ shipping.pk }}">{{ shipping }}</option>
				{% endfor %}
			</select>
		</td>
	</tr>
	<tr class="text-center">
		<td colspan="2"><input type="submit" class="btn btn-outline-success"></td>
	</tr>
</table>
</form>
{% load static %}
<script src="{% static 'books/bookaddedit.js' %}"></script>
{% endblock %}

books/templates/books/books.html
{% extends 'components/base.html' %}
{% block title %}books{% endblock %}
{% block content %}
<div id="content" class="yui3-g">
	<div id="main-column" class="yui3-u-2-3">
		<div id="main-column-content" class="content">
			<h1>The Books</h1>
			<div id="postlist" class="postlist">
				<div class="content">
					{% for book in books  %}
					<div id="NewsArchive-0" class="item clearfix">
						<div class="clearfix">
							<a href="{% url 'books:viewbook' book.slug %}" title="{{ book.title }}">
								<img src="{{ book.cover_image.url }}" class="align-left thumbnail" alt="book cover">
							</a>
							<div class="post-hd">
								<h2><a href="{% url 'books:viewbook' book.slug %}" title="{{ book.title }}">{{ book.name }}</a></h2>
							</div>
							<p class="blurb">{{ book.description }}</p>
						</div>
						<footer>
							<div>
								{% if book.sample_book %}
									<p class="button"><a href="{{ book.sample_book.url }}" title="sample chapters: {{ book.name }}" target="_blank" rel="nofollow">Sample Chapters</a></p>
								{% endif %}
								{% if book.audio_price %}
									 <p class="button"><a href="{% url 'books:addtocart' book.slug %}?ptype=audio" rel="nofollow">Audio</a></p>
								{% endif %}
								{% if book.ebook_price %}
									<p class="button" title="Add to cart"><a href="{% url 'books:addtocart' book.slug %}?ptype=ebook" rel="nofollow">Ebook</a></p>
								{% endif %}
								{% if book.paperback and book.paperback_quantity > 0 %}
								<p class="button"><a href="{% url 'books:addtocart' book.slug %}?ptype=paperback" rel="nofollow">Paperback</a></p>
								{% endif %}
							</div>
						</footer>
					</div>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
</div><!--content-->


{% endblock %}

books/templates/books/edit_book.html
{% extends 'accounts/baseAccount.html' %}
{% block content %}
<form method="post" enctype="multipart/form-data">
<table class="table table-borderless table-hover container">
	{% csrf_token %}
	<tr>
		<td>Name</td>
		<td><input type="text" name="name" class="form-control" value="{{ book.name }}"></td>
	</tr>
	<tr>
		<td>Description</td>
		<td><textarea name="description" cols="30" rows="4" class="form-control">{{ book.description }}</textarea></td>
	</tr>
	<tr>
		<td><label for="active">active</label></td>
		<td><input type="checkbox" id="active" name="active" {% if book.active %}checked{% endif %}></td>
	</tr>
	<tr>
		<td>cover image</td>
		<td>
			<a href="{{ book.cover_image.url }}" target="_blank">current</a>
			<input type="file" name="cover_image" class="form-control">
		</td>
	</tr>
	<tr>
		<td>Sample book</td>
		<td>
			<a href="{{ book.sample_book.url }}" target="_blank">current</a>
			<input type="file" name="sample_book" class="form-control">
		</td>
	</tr>
	<tr>
		<td>taxes</td>
		<td>
			<select name="taxes" class="form-control" multiple>
				{% for tax in taxes %}
				<option value="{{ tax.pk }}" {% if tax in book.taxes.all %} selected  {% endif %}>{{tax.name}} {{tax.percentage}}%</option>
				{% endfor %}
			</select>
		</td>
	</tr>
	<tr>
		<td>audio </td>
		<td>
			{% if book.audio %}
			<a href="{{ book.audio.url }}" target="_blank">current</a>
			{% endif %}
			<input type="file" name="audio" class="form-control">
		</td>
	</tr>
	<tr>
		<td>audio price</td>
		<td><input type="number" name="audio_price" class="form-control" value="{{ book.audio_price }}"></td>
	</tr>
	<tr>
		<td>ebook</td>
		<td>
			{% if book.digital %}
			<a href="{{ book.digital.url }}" target="_blank">current</a>
			{% endif %}
			<input type="file" name="ebook" class="form-control">
		</td>
	</tr>
	<tr>
		<td>ebook price</td>
		<td><input type="number" name="ebook_price" class="form-control"></td>
	</tr>
	<tr>
		<td><label for="paper_back">paper back</label></td>
		<td><input id="paper_back" type="checkbox" name="paperback" {% if book.paperback %}checked{% endif %}></td>
	</tr>
	<tr class="paperbackRow">
		<td>paperback quantity</td>
		<td><input type="number" name="paperback_quantity" class="form-control" value="{{ book.paperback_quantity }}"></td>
	</tr>
	<tr class="paperbackRow">
		<td>paperback price</td>
		<td><input type="number" name="paperback_price" class="form-control" value="{{ book.paperback_price }}"></td>
	</tr>
	<tr class="paperbackRow">
		<td>Shipping</td>
		<td>
			<select name="shipping" class="form-control">
				<option value="">--select shipping--</option>
				{% for shipping in shippings %}
				<option value="{{ shipping.pk }}" {% if shipping == book.shipping %}selected{% endif %}>{{ shipping }}</option>
				{% endfor %}
			</select>
		</td>
	</tr>
	<tr class="text-center">
		<td colspan="2"><input type="submit" class="btn btn-outline-success"></td>
	</tr>
</table>
</form>

<script>
	function checked(){
		$('.paperbackRow').show();
		$('input[name=paperback_quantity]').prop("required",true)
		$('input[name=paperback_price]').prop("required",true)
		$('select[name=shipping]').prop("required",true)
	}
	function notchecked(){
		$('.paperbackRow').hide();
		$('input[name="paperback_quantity"]').val('');
		$('input[name="paperback_price"]').val('');
		$('select[name="shipping"]').val('');
		$('input[name=paperback_quantity]').prop("required",false)
		$('input[name=paperback_price]').prop("required",false)
		$('select[name=shipping]').prop("required",false)
	}
	$(document).ready(function () {
		if($('#paper_back').prop('checked')){
			checked()		
		}
		else{
			notchecked()
		}
	})
	$('#paper_back').change(function () {
		if($(this).prop('checked')){
			checked()
		}
		else{
			notchecked()
		}
	});
</script>

{% endblock %}

books/templates/books/viewbook.html
{% extends 'components/view_base.html' %}
{% block title %}{{ book.name }}{% endblock %}
{% block content %}
<div id="content" class="yui3-g">
	<div id="main-column" class="yui3-u-2-3">
		<div id="main-column-content" class="content">
			<div id="story-head">
				<div id="headline">
					<h1>{{ book.name }}</h1>
					<a href="{{ book.cover_image.url }}" title="{{ book.title }}" target="_blank" rel="lightbox[splash]">
						<img src="{{ book.cover_image.url }}" class="">
					</a>
					<cite>
					</cite>
				</div>
			</div><!--story-head-->
			<div id="story-body">
				<div id="story">
					<article>
						<div class="content">
							<p>{{ book.description }}</p>
							<p class="button"><a title="Chapters 1 to 3 of {{ book.name }}" href="{{ book.sample_book.url }}" target="_blank"><strong>Click here to read the first three chapters</strong></a></p>
							<h4>Buy the Book</h4>
							<ul>
								{% if book.paperback and book.paperback_quantity > 0  %}
								<li><a title="{{ book.title }}" href="{% url 'books:addtocart' book.slug %}?ptype=paperback" target="_blank">Paperback</a></li>
								{% endif %}
								{% if book.ebook_price %}
								<li><a title="{{ book.title }}" href="{% url 'books:addtocart' book.slug %}?ptype=ebook" target="_blank">Ebook</a></li>
								{% endif %}
								{% if book.audio_price %}
								<li><a title="{{ book.title }}" href="{% url 'books:addtocart' book.slug %}?ptype=audio" target="_blank">Audio book</a></li>
								{% endif %}
							</ul>
						</div>
					</article>
				</div><!--story-->
			</div><!--story-body-->
		</div>
	</div>
		</div><!--content-->
{% endblock %}